import type { Config } from 'tailwindcss'

export default {
  darkMode: ['class'],
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-surface': '#1a1a1a',
        'primary-container': '#ffcc00',
        error: '#cc0000',
        'on-primary-fixed': '#1a1a1a',
        secondary: '#e63b2e',
        'on-primary-fixed-variant': '#1a1a1a',
        'inverse-surface': '#1a1a1a',
        'on-error-container': '#93000a',
        outline: '#1a1a1a',
        'on-tertiary-fixed-variant': '#1a1a1a',
        'inverse-primary': '#f5f0e8',
        'on-tertiary': '#ffffff',
        'tertiary-fixed': '#d6e3ff',
        'on-tertiary-fixed': '#1a1a1a',
        'surface-container-lowest': '#ffffff',
        tertiary: '#0055ff',
        'surface-tint': '#1a1a1a',
        'error-container': '#ffdad6',
        'on-secondary': '#1a1a1a',
        'outline-variant': '#d0cbc3',
        'primary-fixed': '#ffcc00',
        'secondary-container': '#ffdad6',
        'primary-fixed-dim': '#e6b800',
        'on-tertiary-container': '#1a1a1a',
        'surface-container-highest': '#e2ddd4',
        'surface-container-high': '#e8e3da',
        'on-secondary-fixed-variant': '#1a1a1a',
        primary: '#1a1a1a',
        'on-surface-variant': '#4a4a4a',
        'on-background': '#1a1a1a',
        'surface-bright': '#faf7f2',
        surface: '#f5f0e8',
        'tertiary-fixed-dim': '#a8c6ff',
        'on-secondary-container': '#1a1a1a',
        'secondary-fixed-dim': '#ffb3ab',
        'tertiary-container': '#d6e3ff',
        'surface-variant': '#e8e3da',
        'surface-container': '#eee9e0',
        'on-secondary-fixed': '#1a1a1a',
        'on-primary': '#ffffff',
        'on-primary-container': '#1a1a1a',
        background: '#f5f0e8',
        'surface-dim': '#d6d1c9',
        'inverse-on-surface': '#f5f0e8',
        'secondary-fixed': '#ffdad6',
        'on-error': '#ffffff',
        'surface-container-low': '#f2ede5',
        priority: {
          1: '#cc0000',
          2: '#F59E0B',
          3: '#10B981',
          4: '#0055ff',
        },
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'space-1': 'var(--space-1)',
        'space-2': 'var(--space-2)',
        'space-3': 'var(--space-3)',
        'space-4': 'var(--space-4)',
        'space-5': 'var(--space-5)',
        'space-6': 'var(--space-6)',
        'space-8': 'var(--space-8)',
        'page-padding': '16px',
        'stack-md': '16px',
        gutter: '12px',
        'stack-lg': '24px',
        'touch-target-min': '48px',
        'stack-sm': '8px',
      },
      fontFamily: {
        'headline-lg': ['Inter'],
        'label-sm': ['Inter'],
        'body-md': ['Inter'],
        'body-lg': ['Inter'],
        'label-md': ['Inter'],
        'headline-md': ['Inter'],
        headline: ['Space Grotesk'],
        display: ['Space Grotesk'],
        body: ['Inter'],
        label: ['Space Grotesk'],
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['13px', { lineHeight: '18px', letterSpacing: '0.01em', fontWeight: '500' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
      },
      keyframes: {
        pulse: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.5' },
        },
        'pulse-glow': {
          '0%, 100%': { opacity: '1', transform: 'scale(1)' },
          '50%': { opacity: '0.6', transform: 'scale(1.1)' },
        },
        'slide-up': {
          from: { transform: 'translateY(100%)' },
          to: { transform: 'translateY(0)' },
        },
      },
      animation: {
        'active-pulse': 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'pulse-glow': 'pulse-glow 2s infinite ease-in-out',
        'slide-up': 'slide-up 0.3s cubic-bezier(0.16, 1, 0.3, 1)',
      },
    },
  },
  plugins: [],
} satisfies Config
